Repository CleverCloud/clever-components, pull requests merged in 2025-09, with the labels that each got.

#1501 feat(cc-addon-header): init component
  demo-smart/index.html
  src/components/cc-addon-header/cc-addon-header.events.js
  src/components/cc-addon-header/cc-addon-header.js
  src/components/cc-addon-header/cc-addon-header.smart-keycloak.js
  src/components/cc-addon-header/cc-addon-header.smart-keycloak.md
  src/components/cc-addon-header/cc-addon-header.stories.js
  src/components/cc-addon-header/cc-addon-header.types.d.ts
  src/lib/events-map.types.d.ts
  src/stories/fixtures/addon.js
  src/translations/translations.en.js
  src/translations/translations.fr.js
Labels: ready-to-merge

#1526 feat(cc-env-var-linked-services): display CLI examples
  demo-smart/index.html
  src/components/cc-env-var-form/cc-env-var-form.js
  src/components/cc-env-var-form/cc-env-var-form.stories.js
  src/components/cc-env-var-form/cc-env-var-form.types.d.ts
  src/components/cc-env-var-linked-services/cc-env-var-linked-services.js
  src/components/cc-env-var-linked-services/cc-env-var-linked-services.smart-addon.js
  src/components/cc-env-var-linked-services/cc-env-var-linked-services.smart-addon.md
  src/components/cc-env-var-linked-services/cc-env-var-linked-services.smart-app.js
  src/components/cc-env-var-linked-services/cc-env-var-linked-services.smart-app.md
  src/components/cc-env-var-linked-services/cc-env-var-linked-services.smart.js
  src/components/cc-env-var-linked-services/cc-env-var-linked-services.stories.js
  src/components/cc-env-var-linked-services/cc-env-var-linked-services.types.d.ts
Labels: enhancement, breaking-change, maintenance

#1552 refactor(cc-addon-info): add missing latest version in addon info stories
  src/components/cc-addon-info/cc-addon-info.js
  src/stories/fixtures/addon-info.js
Labels: run-visual-tests

#1548 feat(cc-addon-credentials-content): make credentials labels more responsive
  src/components/cc-addon-credentials-content/cc-addon-credentials-content.js
Labels: run-visual-tests

#1558 ci(visual-tests): refactor GitHub PR comment management scripts into a unified CLI
  .github/scripts/comment-utils.js
  .github/scripts/create-or-edit-comment.js
  .github/scripts/delete-comment.js
  .github/scripts/manage-comment.js
  .github/workflows/manage-visual-tests.yml
  test/helpers/story-testing-utils.js
Labels: run-visual-tests

#1559 ci(visual-tests): prevent clean up failure
  .github/workflows/manage-visual-tests.yml
Labels: run-visual-tests
