Repository CleverCloud/clever-components, pull requests merged in 2025-03, with the labels that each got.

#1350 chore(master): release 18.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#1353 feat(cc-date-range-selector): move custom date range form inside popover body
  sandbox/cc-logs-app-runtime/cc-logs-app-runtime-sandbox.js
  src/components/cc-logs-app-runtime/cc-logs-app-runtime.js
  src/components/cc-logs-control/cc-logs-control.js
  src/components/cc-logs-control/cc-logs-control.stories.js
  src/components/cc-logs-date-range-selector/cc-logs-date-range-selector.js
  src/components/cc-logs-date-range-selector/cc-logs-date-range-selector.stories.js
  src/components/cc-popover/cc-popover.js
Labels: enhancement

#1361 ci(code-quality): add a check on the commit messages
  .github/workflows/test-and-build.yml
Labels: ci/cd

#1358 feat(cc-logs-app-access): add date range selector
  sandbox/cc-logs-app-access/cc-logs-app-access-sandbox.js
  src/components/cc-logs-app-access/cc-logs-app-access.js
  src/components/cc-logs-app-access/cc-logs-app-access.smart.js
  src/components/cc-logs-app-access/cc-logs-app-access.smart.md
Labels: enhancement

#1352 chore(master): release 18.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending
